# Generated by Django 3.1 on 2020-08-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='排队日期')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=50, unique=True, verbose_name='微信openId')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='用户消息')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='testQue.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserBarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='条形码')),
                ('create_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='testQue.date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='testQue.user')),
            ],
        ),
        migrations.CreateModel(
            name='QueInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(verbose_name='排名')),
                ('status', models.IntegerField(choices=[(0, '未完成'), (1, '已完成')], default=0, verbose_name='是否完成')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='que_info', to='testQue.date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='testQue.user')),
            ],
        ),
    ]
